version: '3.8'

services:
  apigateway:
    build:
      context: ./ApiGateway
    ports:
      - "8088:8088"

  productservice:
    build:
      context: ./ProductModule
    ports:
      - "8082:8082"
    depends_on:
      - postgres1
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres1:5432/product
      SPRING_DATASOURCE_USERNAME: "postgres"
      SPRING_DATASOURCE_PASSWORD: "Gereksiz123"
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

  saleservice:
    build:
      context: ./SaleModule
    ports:
      - "8080:8080"
    depends_on:
      - postgres2
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres2:5432/sale
      SPRING_DATASOURCE_USERNAME: "postgres"
      SPRING_DATASOURCE_PASSWORD: "Gereksiz123"
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

  raporservice:
    build:
      context: ./RaporModule
    ports:
      - "8085:8085"
    depends_on:
      - postgres3
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres3:5432/rapor
      SPRING_DATASOURCE_USERNAME: "postgres"
      SPRING_DATASOURCE_PASSWORD: "Gereksiz123"
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

  postgres1:
    container_name: postgres_db1
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=Gereksiz123
      - POSTGRES_USER=postgres
      - POSTGRES_DB=product
    volumes:
      - postgres_data1:/var/lib/postgresql/data

  postgres2:
    container_name: postgres_db2
    image: postgres
    ports:
      - "5444:5432"
    environment:
      - POSTGRES_PASSWORD=Gereksiz123
      - POSTGRES_USER=postgres
      - POSTGRES_DB=sale
    volumes:
      - postgres_data2:/var/lib/postgresql/data

  postgres3:
    container_name: postgres_db3
    image: postgres
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_PASSWORD=Gereksiz123
      - POSTGRES_USER=postgres
      - POSTGRES_DB=rapor
    volumes:
      - postgres_data3:/var/lib/postgresql/data

volumes:
  postgres_data1:
  postgres_data2:
  postgres_data3:
