version: '3.8'

services:
  spring-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring-docker-salemodule
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/sale
      SPRING_DATASOURCE_USERNAME: "postgres"
      SPRING_DATASOURCE_PASSWORD: "Gereksiz123"
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

  postgres:
    container_name: postgres_db
    image: postgres
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_PASSWORD=Gereksiz123
      - POSTGRES_USER=postgres
      - POSTGRES_DB=sale
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
